x-environment:
  &default-back-environment
  # Django settings
  DJANGO_DEBUG: "${DJANGO_DEBUG:-False}"
  DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE:-settings.config}"
  # Database settings
  POSTGRES_DB: "${POSTGRES_DB:-taiga}"
  POSTGRES_USER: "${POSTGRES_USER:-taiga}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-taiga}"
  POSTGRES_HOST: "taiga-db"
  POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
  # Taiga settings
  TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY:-a2fb3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t}"
  TAIGA_SITES_SCHEME: "${TAIGA_SITES_SCHEME:-http}"
  TAIGA_SITES_DOMAIN: "${TAIGA_SITES_DOMAIN:-localhost:8000}"
  FORCE_SCRIPT_NAME: "${FORCE_SCRIPT_NAME:-}"
  # Email settings
  EMAIL_BACKEND: "${EMAIL_BACKEND:-django.core.mail.backends.console.EmailBackend}"
  DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL:-no-reply@example.com}"
  EMAIL_USE_TLS: "${EMAIL_USE_TLS:-False}"
  EMAIL_USE_SSL: "${EMAIL_USE_SSL:-False}"
  EMAIL_HOST: "${EMAIL_HOST:-localhost}"
  EMAIL_PORT: "${EMAIL_PORT:-25}"
  EMAIL_HOST_USER: "${EMAIL_HOST_USER:-}"
  EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD:-}"
  # Rabbitmq settings
  RABBITMQ_USER: "${RABBITMQ_USER:-taiga}"
  RABBITMQ_PASS: "${RABBITMQ_PASS:-taiga}"
  TAIGA_ASYNC_RABBITMQ_HOST: "taiga-async-rabbitmq"
  TAIGA_EVENTS_RABBITMQ_HOST: "taiga-events-rabbitmq"
  RABBITMQ_VHOST: "taiga"
  # Feature flags
  CELERY_ENABLED: "${CELERY_ENABLED:-True}"
  ENABLE_TELEMETRY: "${ENABLE_TELEMETRY:-False}"
  PUBLIC_REGISTER_ENABLED: "${PUBLIC_REGISTER_ENABLED:-True}"
  WEBHOOKS_ENABLED: "${WEBHOOKS_ENABLED:-False}"
  FEEDBACK_ENABLED: "${FEEDBACK_ENABLED:-False}"
  STATS_ENABLED: "${STATS_ENABLED:-False}"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-taiga}"
      POSTGRES_USER: "${POSTGRES_USER:-taiga}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-taiga}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-taiga}"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes:
      - taiga-media-data:/taiga-back/media
    ports:
      - "8000:8000"
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes:
      - taiga-media-data:/taiga-back/media
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE:-secret_cookie}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-taiga}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-taiga}"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE:-secret_cookie}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-taiga}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-taiga}"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "${ATTACHMENTS_MAX_AGE:-360}"
      SECRET_KEY: "${TAIGA_SECRET_KEY:-a2fb3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t}"
    networks:
      - taiga

volumes:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga: