services:
  # Frontend - expose directly on port 3000 for Zeabur's Caddy
  frontend:
    image: rstubryan/tascrum-frontend:latest
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_BASE_URL_BLOG=${NEXT_PUBLIC_BASE_URL_BLOG}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - traefik-public

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - traefik-public
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - traefik-public
    ports:
      - "9090:9090"

networks:
  traefik-public:
    driver: overlay
    attachable: true

volumes:
  grafana-data:
  prometheus-data: